// Mock Data for Testing Alromaih Cars Dashboard
import type { Car, Brand, DashboardStats, CarOffer } from "./types"

export const mockBrands: Brand[] = [
  {
    id: "1",
    name: "Toyota",
    description: "Japanese automotive manufacturer",
    logo: "/placeholder.svg?height=40&width=40",
    website: "https://toyota.com",
    country_of_origin: "Japan",
    established_year: 1937,
    active: true,
    sequence: 10,
  },
  {
    id: "2",
    name: "BMW",
    description: "German luxury automotive manufacturer",
    logo: "/placeholder.svg?height=40&width=40",
    website: "https://bmw.com",
    country_of_origin: "Germany",
    established_year: 1916,
    active: true,
    sequence: 20,
  },
  {
    id: "3",
    name: "Mercedes-Benz",
    description: "German luxury automotive manufacturer",
    logo: "/placeholder.svg?height=40&width=40",
    website: "https://mercedes-benz.com",
    country_of_origin: "Germany",
    established_year: 1926,
    active: true,
    sequence: 30,
  },
  {
    id: "4",
    name: "Audi",
    description: "German luxury automotive manufacturer",
    logo: "/placeholder.svg?height=40&width=40",
    website: "https://audi.com",
    country_of_origin: "Germany",
    established_year: 1909,
    active: true,
    sequence: 40,
  },
]

export const mockCars: Car[] = [
  {
    id: "1",
    name: "Toyota Camry 2024",
    status: "published",
    cash_price: 85000,
    cash_price_with_vat: 97750,
    finance_price: 95000,
    vat_percentage: 15,
    is_featured: true,
    has_active_offer: true,
    specification_completion: 95,
    active: true,
    sequence: 10,
    thumbnail: "/placeholder.svg?height=200&width=300",
    brand_id: mockBrands[0],
    model_id: { id: "1", name: "Camry", description: "Mid-size sedan", brand_id: mockBrands[0] },
    trim_id: { id: "1", name: "LE", description: "Base trim level" },
    year_id: { id: "1", name: "2024", year_value: 2024 },
    primary_color_id: { id: "1", name: "Pearl White", color_code: "#FFFFFF" },
    specification_ids: [],
    media_ids: [],
    offer_ids: [],
    variant_ids: [],
  },
  {
    id: "2",
    name: "BMW X5 2024",
    status: "published",
    cash_price: 320000,
    cash_price_with_vat: 368000,
    finance_price: 340000,
    vat_percentage: 15,
    is_featured: true,
    has_active_offer: false,
    specification_completion: 88,
    active: true,
    sequence: 20,
    thumbnail: "/placeholder.svg?height=200&width=300",
    brand_id: mockBrands[1],
    model_id: { id: "2", name: "X5", description: "Luxury SUV", brand_id: mockBrands[1] },
    trim_id: { id: "2", name: "xDrive40i", description: "Premium trim" },
    year_id: { id: "1", name: "2024", year_value: 2024 },
    primary_color_id: { id: "2", name: "Jet Black", color_code: "#000000" },
    specification_ids: [],
    media_ids: [],
    offer_ids: [],
    variant_ids: [],
  },
  {
    id: "3",
    name: "Mercedes-Benz C-Class 2024",
    status: "draft",
    cash_price: 180000,
    cash_price_with_vat: 207000,
    finance_price: 190000,
    vat_percentage: 15,
    is_featured: false,
    has_active_offer: true,
    specification_completion: 72,
    active: true,
    sequence: 30,
    thumbnail: "/placeholder.svg?height=200&width=300",
    brand_id: mockBrands[2],
    model_id: { id: "3", name: "C-Class", description: "Luxury sedan", brand_id: mockBrands[2] },
    trim_id: { id: "3", name: "C300", description: "Base luxury trim" },
    year_id: { id: "1", name: "2024", year_value: 2024 },
    primary_color_id: { id: "3", name: "Silver Metallic", color_code: "#C0C0C0" },
    specification_ids: [],
    media_ids: [],
    offer_ids: [],
    variant_ids: [],
  },
]

export const mockOffers: CarOffer[] = [
  {
    id: "1",
    name: "Summer Sale 2024",
    description: "Special summer discount on selected cars",
    discount_type: "percentage",
    discount_value: 10,
    original_price: 85000,
    final_price: 76500,
    start_date: "2024-06-01",
    end_date: "2024-08-31",
    is_active: true,
    offer_tag: "hot_deal",
    apply_to_all_variants: true,
  },
  {
    id: "2",
    name: "Luxury Car Promotion",
    description: "Fixed discount on luxury vehicles",
    discount_type: "fixed",
    discount_value: 15000,
    original_price: 180000,
    final_price: 165000,
    start_date: "2024-07-01",
    end_date: "2024-09-30",
    is_active: true,
    offer_tag: "limited_time",
    apply_to_all_variants: false,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalCars: 156,
  totalBrands: 12,
  totalOffers: 8,
  totalVariants: 324,
  featuredCars: 24,
  publishedCars: 142,
  draftCars: 14,
  activeOffers: 6,
  totalRevenue: 12500000,
  monthlyRevenue: 2100000,
}

export const mockRecentActivity = [
  {
    id: "1",
    type: "car_created",
    message: 'New car "Toyota Prius 2024" was created',
    timestamp: "2024-01-15T10:30:00Z",
    user: "Ahmed Al-Rashid",
  },
  {
    id: "2",
    type: "offer_activated",
    message: "Summer Sale 2024 offer was activated",
    timestamp: "2024-01-15T09:15:00Z",
    user: "Sara Al-Mahmoud",
  },
  {
    id: "3",
    type: "car_published",
    message: "BMW X3 2024 was published",
    timestamp: "2024-01-15T08:45:00Z",
    user: "Mohammed Al-Fahad",
  },
  {
    id: "4",
    type: "media_uploaded",
    message: "5 new images uploaded for Mercedes E-Class",
    timestamp: "2024-01-15T08:20:00Z",
    user: "Fatima Al-Zahra",
  },
]
